"""Renderers for the reconciliation report: markdown and single-file HTML.

The HTML file is the demo artifact: self-contained, inline CSS, an inline
SVG bar chart generated by code, no external assets, prints clean to PDF.
Tone is plain and factual throughout.
"""

import html
from datetime import date
from decimal import Decimal

from .report import MethodRow, ReconciliationReport

FOOTER = "Deterministic math. Every number computed by code from the deal export."
ROUNDING_NOTE = (
    "Monthly figures are shown rounded to the cent; totals are computed on the "
    "unrounded values, so summing a printed column can differ from its total by a cent."
)


def _money(value: Decimal) -> str:
    return f"${value:,.2f}"


def _pct(value: Decimal) -> str:
    return f"{value:+.1f}%"


def _headline_lines(report: ReconciliationReport) -> list[str]:
    presented = report.presented
    lines = [
        f"Projected {report.horizon}-month commission ({presented.label}): "
        f"{_money(presented.total)}"
    ]
    if report.target_low is not None and report.target_high is not None:
        lines.append(
            f"Client's expected range: {_money(report.target_low)} – {_money(report.target_high)}"
        )
        variance = report.headline_variance_pct
        if report.headline_in_range:
            lines.append("The projection falls inside the client's expected range.")
        elif variance < 0:
            lines.append(f"Variance: {variance:+.1f}% below the range floor.")
        else:
            lines.append(f"Variance: {variance:+.1f}% above the range ceiling.")
    first = report.historical[0].month
    last = report.historical[-1].month
    lines.append(
        f"Recorded history: {len(report.historical)} months "
        f"({first:%b %Y} – {last:%b %Y}), total {_money(report.historical_total)}."
    )
    return lines


def _method_cells(row: MethodRow) -> tuple[str, str, str]:
    if row.error is not None:
        return (f"could not run: {row.error}", "—", "—")
    variance = "—" if row.variance_vs_midpoint_pct is None else _pct(row.variance_vs_midpoint_pct)
    in_range = "—" if row.in_range is None else ("yes" if row.in_range else "no")
    return (_money(row.total), variance, in_range)


# ---------------------------------------------------------------- markdown


def render_markdown(report: ReconciliationReport) -> str:
    out: list[str] = []
    out.append(f"# {report.client_name} — commission forecast reconciliation")
    meta = [f"As of {report.as_of:%d %b %Y}"]
    if report.rule_description:
        meta.append(f"commission rule: {report.rule_description}")
    meta.append(f"projection horizon: {report.horizon} months")
    out.append(" · ".join(meta))
    out.append("")

    out.append("## A. Headline")
    out.append("")
    for line in _headline_lines(report):
        out.append(line + "  ")
    out.append("")

    out.append("## B. Method table")
    out.append("")
    mid = report.target_mid
    vs_label = f"vs midpoint ({_money(mid)})" if mid is not None else "vs midpoint"
    out.append(f"| Method | {report.horizon}-mo total | {vs_label} | In range | |")
    out.append("|---|---:|---:|:--:|---|")
    for row in report.methods:
        total, variance, in_range = _method_cells(row)
        marker = "**presented**" if row.presented else ""
        out.append(f"| {row.label} | {total} | {variance} | {in_range} | {marker} |")
    out.append("")
    out.append(f"Presented method rationale: {report.presented.rationale}")
    out.append("")
    out.append(
        "Every method is computed and shown; none is discarded. "
        "The presented method is a choice, stated above, not a hidden fit."
    )
    out.append("")

    out.append("## C. Monthly view")
    out.append("")
    out.append("### Recorded months")
    out.append("")
    out.append("| Month | Deals | Gross | Commission |")
    out.append("|---|---:|---:|---:|")
    for entry in report.historical:
        out.append(
            f"| {entry.month:%b %Y} | {entry.deal_count} | "
            f"{_money(entry.gross)} | {_money(entry.commission_2dp)} |"
        )
    out.append(f"| **Total** | | | **{_money(report.historical_total)}** |")
    out.append("")
    out.append(f"### Projected months ({report.presented.label})")
    out.append("")
    out.append("| Month | Commission (projected) |")
    out.append("|---|---:|")
    for month, value in report.projected:
        out.append(f"| {month:%b %Y} | {_money(value)} |")
    out.append(f"| **{report.horizon}-month total** | **{_money(report.presented.total)}** |")
    out.append("")
    out.append(ROUNDING_NOTE)
    out.append("")

    out.append("## D. Confirm with client")
    out.append("")
    if report.flags:
        for i, flag in enumerate(report.flags, start=1):
            out.append(f"{i}. {flag.question}")
            if flag.detail:
                out.append(f"   ({flag.detail})")
    else:
        out.append("No flags raised by this run.")
    out.append("")
    out.append("---")
    out.append(FOOTER)
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------- inline SVG chart

# palette (light surface), validated: recorded #2a78d6, projected #86b6ef
BAR_RECORDED = "#2a78d6"
BAR_PROJECTED = "#86b6ef"
INK_MUTED = "#898781"
GRID = "#e1e0d9"
BASELINE = "#c3c2b7"


def _nice_step(raw: float) -> float:
    magnitude = 10 ** len(str(int(raw))) / 10
    for factor in (1, 2, 2.5, 5, 10):
        if factor * magnitude >= raw:
            return factor * magnitude
    return 10 * magnitude


def _svg_chart(report: ReconciliationReport) -> str:
    bars: list[tuple[date, float, bool]] = [
        (e.month, float(e.commission_2dp), False) for e in report.historical
    ]
    bars += [(month, float(value), True) for month, value in report.projected]

    width, height = 960, 300
    left, right, top, bottom = 64, 16, 20, 44
    plot_w, plot_h = width - left - right, height - top - bottom

    peak = max(v for _, v, _ in bars)
    step = _nice_step(peak / 4)
    ticks = 0
    while ticks * step < peak:
        ticks += 1
    y_max = ticks * step

    def y_px(value: float) -> float:
        return top + plot_h * (1 - value / y_max)

    band = plot_w / len(bars)
    bar_w = min(24.0, band - 2)

    parts: list[str] = [
        f'<svg viewBox="0 0 {width} {height}" role="img" '
        f'aria-label="Monthly commission, recorded then projected" '
        f'xmlns="http://www.w3.org/2000/svg">'
    ]

    # gridlines + y tick labels
    for t in range(ticks + 1):
        value = t * step
        y = y_px(value)
        if t > 0:
            parts.append(
                f'<line x1="{left}" y1="{y:.1f}" x2="{width - right}" y2="{y:.1f}" '
                f'stroke="{GRID}" stroke-width="1"/>'
            )
        parts.append(
            f'<text x="{left - 8}" y="{y + 3.5:.1f}" text-anchor="end" '
            f'font-size="11" fill="{INK_MUTED}">{value:,.0f}</text>'
        )

    # boundary between recorded and projected
    boundary_x = left + band * len(report.historical)
    parts.append(
        f'<line x1="{boundary_x:.1f}" y1="{top}" x2="{boundary_x:.1f}" '
        f'y2="{top + plot_h}" stroke="{BASELINE}" stroke-width="1"/>'
    )

    # bars: 4px rounded data-end, square at the baseline
    base_y = top + plot_h
    for i, (month, value, projected) in enumerate(bars):
        x = left + band * i + (band - bar_w) / 2
        bar_top = y_px(value)
        h = base_y - bar_top
        r = min(4.0, h, bar_w / 2)
        fill = BAR_PROJECTED if projected else BAR_RECORDED
        kind = "projected" if projected else "recorded"
        path = (
            f"M{x:.1f},{base_y:.1f} "
            f"L{x:.1f},{bar_top + r:.1f} "
            f"Q{x:.1f},{bar_top:.1f} {x + r:.1f},{bar_top:.1f} "
            f"L{x + bar_w - r:.1f},{bar_top:.1f} "
            f"Q{x + bar_w:.1f},{bar_top:.1f} {x + bar_w:.1f},{bar_top + r:.1f} "
            f"L{x + bar_w:.1f},{base_y:.1f} Z"
        )
        title = f"{month:%B %Y} — ${value:,.2f} {kind}"
        parts.append(f'<path d="{path}" fill="{fill}"><title>{html.escape(title)}</title></path>')

    # baseline on top of the bars' square ends
    parts.append(
        f'<line x1="{left}" y1="{base_y:.1f}" x2="{width - right}" y2="{base_y:.1f}" '
        f'stroke="{BASELINE}" stroke-width="1"/>'
    )

    # x labels: quarter months only, to keep 26 columns readable
    for i, (month, _, _) in enumerate(bars):
        if month.month in (1, 4, 7, 10):
            cx = left + band * i + band / 2
            parts.append(
                f'<text x="{cx:.1f}" y="{base_y + 16:.1f}" text-anchor="middle" '
                f'font-size="10" fill="{INK_MUTED}">{month:%b %y}</text>'
            )

    parts.append("</svg>")
    return "".join(parts)


# ---------------------------------------------------------------- html

CSS = """
:root {
  --surface: #fcfcfb;
  --page: #f9f9f7;
  --ink: #0b0b0b;
  --ink-2: #52514e;
  --muted: #898781;
  --grid: #e1e0d9;
  --hairline: rgba(11, 11, 11, 0.10);
  --recorded: #2a78d6;
  --projected: #86b6ef;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
}
.page {
  max-width: 900px;
  margin: 0 auto;
  padding: 32px 36px 24px;
  background: var(--surface);
  min-height: 100vh;
}
header { margin-bottom: 24px; }
h1 { font-size: 20px; margin: 0 0 4px; }
.meta { color: var(--ink-2); font-size: 13px; }
section { margin: 26px 0; break-inside: avoid; }
h2 {
  font-size: 12px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--ink-2);
  border-bottom: 1px solid var(--grid);
  padding-bottom: 6px;
  margin: 0 0 12px;
}
.headline-label { color: var(--ink-2); font-size: 13px; }
.headline-figure { font-size: 34px; font-weight: 600; margin: 2px 0 6px; }
.headline-lines p { margin: 4px 0; }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th, td { padding: 6px 10px; text-align: left; border-bottom: 1px solid var(--grid); }
th { color: var(--ink-2); font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
td.center, th.center { text-align: center; }
tr.presented td { background: #eef4fc; }
tr.presented td:first-child { border-left: 3px solid var(--recorded); }
.chip {
  font-size: 11px;
  color: var(--ink-2);
  border: 1px solid var(--hairline);
  border-radius: 3px;
  padding: 1px 6px;
  white-space: nowrap;
}
tfoot td { font-weight: 600; border-bottom: none; }
.rationale { color: var(--ink-2); font-size: 13px; margin-top: 10px; }
.note { color: var(--muted); font-size: 12px; margin-top: 6px; }
.legend { display: flex; gap: 18px; font-size: 12px; color: var(--ink-2); margin: 10px 0 4px; }
.legend .swatch {
  display: inline-block; width: 10px; height: 10px; border-radius: 2px;
  margin-right: 5px; vertical-align: baseline;
}
.chart { margin: 8px 0 4px; }
.chart svg { width: 100%; height: auto; display: block; }
.cols { display: flex; gap: 28px; flex-wrap: wrap; }
.cols > div { flex: 1 1 280px; }
ol.flags { margin: 0; padding-left: 20px; }
ol.flags li { margin: 8px 0; }
ol.flags .detail { color: var(--muted); font-size: 12px; }
footer {
  margin-top: 32px;
  padding-top: 10px;
  border-top: 1px solid var(--grid);
  color: var(--muted);
  font-size: 12px;
}
@media print {
  body { background: #fff; }
  .page { max-width: none; min-height: 0; padding: 0; }
  section { break-inside: avoid; }
}
"""


def render_html(report: ReconciliationReport) -> str:
    esc = html.escape
    presented = report.presented
    headline = _headline_lines(report)

    out: list[str] = []
    out.append("<!doctype html>")
    out.append('<html lang="en"><head><meta charset="utf-8">')
    out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    out.append(f"<title>{esc(report.client_name)} — commission forecast reconciliation</title>")
    out.append(f"<style>{CSS}</style></head><body>")
    out.append('<div class="page">')

    out.append("<header>")
    out.append(f"<h1>{esc(report.client_name)} — commission forecast reconciliation</h1>")
    meta = [f"As of {report.as_of:%d %b %Y}"]
    if report.rule_description:
        meta.append(f"commission rule: {esc(report.rule_description)}")
    meta.append(f"projection horizon: {report.horizon} months")
    out.append(f'<div class="meta">{" · ".join(meta)}</div>')
    out.append("</header>")

    # A. headline
    out.append("<section>")
    out.append("<h2>A. Headline</h2>")
    out.append(
        f'<div class="headline-label">Projected {report.horizon}-month commission '
        f"({esc(presented.label)})</div>"
    )
    out.append(f'<div class="headline-figure">{esc(_money(presented.total))}</div>')
    out.append('<div class="headline-lines">')
    for line in headline[1:]:
        out.append(f"<p>{esc(line)}</p>")
    out.append("</div></section>")

    # B. method table
    out.append("<section>")
    out.append("<h2>B. Method table — every method, nothing discarded</h2>")
    mid = report.target_mid
    vs_label = f"vs midpoint ({_money(mid)})" if mid is not None else "vs midpoint"
    out.append("<table><thead><tr>")
    out.append(
        f'<th>Method</th><th class="num">{report.horizon}-mo total</th>'
        f'<th class="num">{esc(vs_label)}</th><th class="center">In range</th><th></th>'
    )
    out.append("</tr></thead><tbody>")
    for row in report.methods:
        total, variance, in_range = _method_cells(row)
        cls = ' class="presented"' if row.presented else ""
        chip = '<span class="chip">presented</span>' if row.presented else ""
        out.append(
            f"<tr{cls}><td>{esc(row.label)}</td>"
            f'<td class="num">{esc(total)}</td>'
            f'<td class="num">{esc(variance)}</td>'
            f'<td class="center">{esc(in_range)}</td>'
            f"<td>{chip}</td></tr>"
        )
    out.append("</tbody></table>")
    out.append(f'<p class="rationale">Presented method rationale: {esc(presented.rationale)}</p>')
    out.append(
        '<p class="note">Every method is computed and shown; none is discarded. '
        "The presented method is a choice, stated above, not a hidden fit.</p>"
    )
    out.append("</section>")

    # C. monthly view
    out.append("<section>")
    out.append("<h2>C. Monthly view</h2>")
    out.append('<div class="legend">')
    out.append(
        f'<span><span class="swatch" style="background:{BAR_RECORDED}"></span>Recorded</span>'
    )
    out.append(
        f'<span><span class="swatch" style="background:{BAR_PROJECTED}"></span>'
        f"Projected ({esc(presented.label)})</span>"
    )
    out.append("</div>")
    out.append(f'<div class="chart">{_svg_chart(report)}</div>')

    out.append('<div class="cols">')
    out.append("<div>")
    out.append("<h3>Recorded months</h3>")
    out.append("<table><thead><tr><th>Month</th>")
    out.append('<th class="num">Deals</th><th class="num">Gross</th>')
    out.append('<th class="num">Commission</th></tr></thead><tbody>')
    for entry in report.historical:
        out.append(
            f"<tr><td>{entry.month:%b %Y}</td>"
            f'<td class="num">{entry.deal_count}</td>'
            f'<td class="num">{esc(_money(entry.gross))}</td>'
            f'<td class="num">{esc(_money(entry.commission_2dp))}</td></tr>'
        )
    out.append(
        f"</tbody><tfoot><tr><td>Total</td><td></td><td></td>"
        f'<td class="num">{esc(_money(report.historical_total))}</td></tr></tfoot></table>'
    )
    out.append("</div>")

    out.append("<div>")
    out.append(f"<h3>Projected months ({esc(presented.label)})</h3>")
    out.append(
        '<table><thead><tr><th>Month</th><th class="num">Commission (projected)</th>'
        "</tr></thead><tbody>"
    )
    for month, value in report.projected:
        out.append(f'<tr><td>{month:%b %Y}</td><td class="num">{esc(_money(value))}</td></tr>')
    out.append(
        f"</tbody><tfoot><tr><td>{report.horizon}-month total</td>"
        f'<td class="num">{esc(_money(presented.total))}</td></tr></tfoot></table>'
    )
    out.append("</div></div>")
    out.append(f'<p class="note">{esc(ROUNDING_NOTE)}</p>')
    out.append("</section>")

    # D. flags
    out.append("<section>")
    out.append("<h2>D. Confirm with client</h2>")
    if report.flags:
        out.append('<ol class="flags">')
        for flag in report.flags:
            detail = f' <span class="detail">({esc(flag.detail)})</span>' if flag.detail else ""
            out.append(f"<li>{esc(flag.question)}{detail}</li>")
        out.append("</ol>")
    else:
        out.append("<p>No flags raised by this run.</p>")
    out.append("</section>")

    out.append(f"<footer>{esc(FOOTER)}</footer>")
    out.append("</div></body></html>")
    return "\n".join(out)
